all:
	@mvn clean javafx:run 
lab:
	@mvn clean javafx:run -Djavafx.mainClass="ro.uaic.Compulsory"
homework:
	@mvn clean javafx:run -Djavafx.mainClass="ro.uaic.Homework"
advanced:
	@mvn clean javafx:run -djavafx.mainclass="ro.uaic.advanced"

clean:
	@rm -rf .settings
	@rm -rf target
	@rm .project
	@rm .classpath
