all:
	@mvn exec:java -Dexec.mainClass="ro.uaic.App" -Dexec.args="1"

lab:
	@mvn exec:java -Dexec.mainClass="ro.uaic.App" -Dexec.args="1"
homework:
	@mvn exec:java -Dexec.mainClass="ro.uaic.App" -Dexec.args="2"
advanced:
	@mvn exec:java -Dexec.mainClass="ro.uaic.App" -Dexec.args="3"

clean:
	@rm -rf .settings
	@rm -rf target
	@rm .project
	@rm .classpath
