all:
	@mvn exec:java -Dexec.mainClass="ro.uaic.Compulsory"

lab:
	@mvn exec:java -Dexec.mainClass="ro.uaic.Compulsory"
homework:
	@mvn exec:java -Dexec.mainClass="ro.uaic.Homework"
advanced:
	@mvn exec:java -Dexec.mainClass="ro.uaic.Advanced"

client:
	@mvn exec:java -Dexec.mainClass="ro.uaic.Client"

clean:
	@rm -rf .settings
	@rm -rf target
	@rm .project
	@rm .classpath
